config/routes.rb
Rails.application.routes.draw do
    root 'products#index'
  
	get     '/login',  to: 'sessions#new'
	post    '/login',  to: 'sessions#create'
	delete  '/logout',  to: 'sessions#destroy'
	
	resources :customers
	resources :products
	

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :customer
	has_many :products	
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products	
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	#attr_accessor :remember_token
	before_save { self.email = email.downcase }
    
	has_many :delivery_addresses
	has_many :orders
	has_many :products, through: :orders
	has_one  :cart

	#validates :first_name, presence: true
	#validates :mobile_number, numericality: {only_integer: true}, length: {is: 10}
	
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	#validates :email, presence: true, length: { maximum: 255 },
    #                format: { with: VALID_EMAIL_REGEX },
    #                uniqueness: { case_sensitive: false }

	#has_secure_password
	#validates :password, presence: true, length: {minimum: 6}, allow_nil: true

	# Returns the hash digest of the given string.
    def Customer.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
	
    # Returns a random token.
	def Customer.new_token
	  SecureRandom.urlsafe_base64
	end
	
=begin	
	# Remembers a customer in the database for use in persistent sessions.
    def remember
      self.remember_token = Customer.new_token
      update_attribute(:remember_digest, Customer.digest(remember_token))
    end
	
	# Returns true if the given token matches the digest.
    def authenticated?(remember_token)
	  return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
	
	# Forgets a customer.
    def forget
	  update_attribute(:remember_digest, nil)
    end
=end
end

app/models/delivery_address.rb
class DeliveryAddress < ActiveRecord::Base
	belongs_to :customer
	has_many :orders	
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer
	has_many :products
	belongs_to :delivery_address
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :order
	belongs_to :cart
	belongs_to :category

	#validates :brand, :name, :size, :color, presence: true
	#validates :price, numericality: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :logged_in_customer, only: [:edit, :update, :destroy]
	before_action :correct_customer,   only: [:edit, :update]
	before_action :admin_customer,     only: :destroy
	
	def index
		@customers = Customer.paginate(page: params[:page])
	end
	
	def show
		@customer = Customer.find(params[:id])
	end
	
	def new
		@customer = Customer.new
	end
	
	def edit
		@customer = Customer.find(params[:id])
	end
	
	def create
		@customer = Customer.new(customer_params)
		if @customer.save
			log_in @customer
            flash[:success] = "Welcome to myMyntra"
			redirect_to @customer
		else
			render 'new'
		end	
	end
	
	def update
		@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
			redirect_to @customer
		else
			render 'edit'
		end
	end
	
	def destroy
		@customer = Customer.find(params[:id])
		@customer.destroy
		flash[:success] = "Customer deleted"
		redirect_to customers_path
	end
	
private 
	def customer_params
		params.require(:customer).permit(:first_name,:last_name,:email,:mobile_number,:password,:password_confirmation)
	end
	
	# Before filters

    # Confirms a logged-in customer.
    def logged_in_customer
      unless logged_in?
	    store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
	
	# Confirms the correct customer.
    def correct_customer
      @customer = Customer.find(params[:id])
      redirect_to(root_url) unless current_customer?(@customer)
    end
	
	# Confirms an administrator.
    def admin_customer
      redirect_to(root_url) unless current_customer.admin?
    end
end

app/controllers/delivery_addresses_controller.rb
class DeliveryAddressesController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
def index
		@orders = Order.all
	end
	
	def show
		@order = Order.find(params[:id])
		
	end
	
	def new
		@order = Order.new
	end
	
	def edit
		@order = Order.find(params[:id])
	end
	
	def create
		@order= Order.new(order_params)
		
		if @order.save
			redirect_to @order
		else
			render 'new'
		end
	end
	
	def update 
		@order = Order.find(params[:id])
		
		if @order.update(order_params)
			redirect_to @order
		else
			render 'edit'
		end
	end
	
	def destroy
		@order = Order.find(params[:id])
		@order.destroy
	
		redirect_to orders_path
	end
	
private
		def order_params
			params.require(:order).permit(:order_quantity,:gross_total) 
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.paginate(page: params[:page])
	end
	
	def show
		@product = Product.find(params[:id])
	end
	
	def new
		@product = Product.new
	end
	
	def edit
		@product = Product.find(params[:id])
	end
	
	def create
#		byebug
		@product = Product.new(product_params)
		
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end
	
	def update 
		@product = Product.find(params[:id])
		
		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end
	
	def destroy
		@product = Product.find(params[:id])
		@product.destroy
	
		redirect_to products_path
	end
	
private
		def product_params
			params.require(:product).permit(:brand,:name,:price,:size,:category) 
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
	customer = Customer.find_by(email: params[:session][:email].downcase)
    if customer && customer.authenticate(params[:session][:password])
      log_in customer # equivalent of customer_url(customer)
	  params[:session][:remember_me] == '1' ? remember(customer) : forget(customer)
	  redirect_back_or customer
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
	log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/delivery_addresses_helper.rb
module DeliveryAddressesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given customer.
  def log_in(customer)
	session[:customer_id] = customer.id
  end
  
  # Remembers a customer in a persistent session.
  def remember(customer)
    customer.remember
    cookies.permanent.signed[:customer_id] = customer.id
    cookies.permanent[:remember_token] = customer.remember_token
  end
  
  # Returns true if the given customer is the current customer.
  def current_customer?(customer)
    customer == current_customer
  end
  
  # Returns the customer corresponding to the remember token cookie.
  def current_customer
	if (customer_id = session[:customer_id])
	  @current_customer ||= Customer.find_by(id: customer_id)
    elsif (customer_id = cookies.signed[:customer_id])
	  customer = Customer.find_by(id: customer_id)
		if customer && customer.authenticated?(cookies[:remember_token])
		  log_in customer
		  @current_customer = customer
		end
	end
  end
  
  # Returns true if the customer is logged in, false otherwise .
  def logged_in?
	!current_customer.nil?
  end
  
  # Forgets a persistent session.
  def forget(customer)
    customer.forget
    cookies.delete(:customer_id)
    cookies.delete(:remember_token)
  end
  
  # Logs out the current customer.
  def log_out
	forget(current_customer)
    session.delete(:customer_id)
    @current_customer = nil
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/views/customers/_error_messages.html.erb
<% if @customer.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@customer.errors.count, "error") %>.
    </div>
    <ul>
    <% @customer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<%= form_for (@customer) do |f|%>
			<p>
				<%= render 'error_messages' %>
			</p>
			
			<p>
				<%= f.label      :first_name %> &nbsp;&nbsp;&nbsp;&nbsp;
				<%= f.text_field :first_name, class:'form-control' %>
			</p>

			<p>
				<%= f.label      :last_name %> &nbsp;
				<%= f.text_field :last_name, class:'form-control'  %>
			</p>

			<p>
				<%= f.label       :email %> &nbsp;
				<%= f.email_field :email, class:'form-control'  %>
			</p>

			<p>
				<%= f.label      :mobile_number %> &nbsp;
				<%= f.text_field :mobile_number, class:'form-control' %>
			</p>
			
			<p>
				<%= f.label :password %> &nbsp;
				<%= f.password_field :password, class:'form-control'  %>
			</p>
			
			<p>
				<%= f.label :password_confirmation, "Confirmation" %> &nbsp;
				<%= f.password_field :password_confirmation, class:'form-control'  %>
			</p>
			
			<p>
				<%= f.submit  class: "btn btn-primary" %>
			</p>
		<% end %>
	</div>
</div>

app/views/customers/edit.html.erb
<h1>Edit profile info</h1>

<%= render 'form'%>

app/views/customers/index.html.erb
<h1>List of customers</h1>
<%= will_paginate %>
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>First Name   </th>
				<th>Last  Name   </th>
				<th>Email        </th>
				<th>Mobile Number</th>
				<th>Updated At   </th>
			</tr>
		</thead>
		<tbody>
			<% @customers.each do |customer|%>
				<tr>
					<td><%= customer.first_name    %></td>
					<td><%= customer.last_name     %></td>
					<td><%= customer.email         %></td>
					<td><%= customer.mobile_number %></td>
					<td><%= customer.updated_at    %></td>
					<td><%= link_to 'Show',customer_path(customer),class: "btn btn-xs btn-primary"%></td>
					<% if current_customer.admin? && !current_customer?(customer) %>
						<td><%= link_to 'Destroy', customer_path(customer), method: :delete, data: {confirm: 'Are you
						sure?'},class: "btn btn-xs btn-primary"%></td>
					<% end %>
					</tr>
			<% end %>
		</tbody>	
	</table>
</div>
<%= will_paginate %>

app/views/customers/new.html.erb
<h1>Create your profile</h1>

<%= render 'form'%>

app/views/customers/show.html.erb
<h1>Show Profile detail</h1>

<p>
	First Name 	  : <%= @customer.first_name  	%> <br>
	Last  Name 	  : <%= @customer.last_name     %> <br>
	Email      	  : <%= @customer.email       	%> <br>
	Mobile Number : <%= @customer.mobile_number %> <br>
	<%= link_to 'Edit', edit_customer_path(@customer)%>
	<%= link_to 'Index', customers_path%>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright &copy; 2017 Deshdeep. All rights reserved.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MyMyntra", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
    <% if logged_in? %>
          <li><%= link_to "Customers", customers_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_customer %></li>
              <li><%= link_to "Settings",edit_customer_path(current_customer) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMyntra</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>	  
	</div>	
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<%= form_for (@product) do |f|%>	
			<p>
				<%= f.label      :name%> &nbsp;
				<%= f.text_field :name, class:'form-control' %>
			</p>

			<p>
				<%= f.label      :brand%> &nbsp;
				<%= f.text_field :brand, class:'form-control' %>
			</p>

			<p>
				<%= f.label      :price%> &nbsp;
				<%= f.text_field :price, class:'form-control' %>
			</p>

			<p>
				<%= f.label      :size%> &nbsp;
				<%= f.text_field :size, class:'form-control' %>
			</p>

			<p>
				<%= f.label      :category%> &nbsp;
				<%= f.text_field :category, class:'form-control' %>
			</p>

			<p>
				<%= f.submit class:"btn btn-primary"%>
			</p>
		<% end %>
	</div>
</div>	

app/views/products/edit.html.erb
<h1>Edit Product Detail</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="center jumbotron">
	<h1>All Products</h1>
	<h4>
	<%= link_to 'Add new product',new_product_path, class: "btn btn-lg btn-primary"%>
	</h4>
	<br>
	
</div>

<%= will_paginate %>

<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Brand</th>
				<th>Price</th>
				<th>Size</th>
				<th>Category</th>
				<th>Updated At</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.name %></td>
					<td><%= product.brand %></td>
					<td><%= product.price %></td>
					<td><%= product.size %></td>
					<td><%= product.category %></td>
					<td><%= product.updated_at %></td>
					<td><%= link_to 'Show',product_path(product),class: "btn btn-xs btn-primary"%></td>
					<td><%= link_to 'Buy','#',class: "btn btn-xs btn-primary"%></td>
					<td><%= link_to 'Destroy',product_path(product), method: :delete, data: {confirm: 'Are you sure?'},class: "btn btn-xs btn-primary"%></td>
				</tr>
			<% end %>
		</tbody>	
	</table>
</div>

<%= will_paginate %>

app/views/products/new.html.erb
<h1>Add New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1>Show Current Product Details</h1>
<p>
	Name		: <%= @product.name %><br>
	Brand 		: <%= @product.brand %><br>
	Price 		: <%= @product.price %><br>
	Size    	: <%= @product.size %><br>
	Category 	: <%= @product.category %><br>
	Updated_at  : <%= @product.updated_at%><br>
	<%= link_to 'Edit', edit_product_path(@product)%>
	<%= link_to 'Buy', '#'%>
	<%= link_to 'Index', products_path%>
</p>